### ISSUE TITLE
Adicionar 60ms entre as leituras e usar ISR nas leituras

### ISSUE THREAD

**Issue by iagolirapasssos** [joao0606almeida/OBR2022#2]
Adicionar uma ISR e delay de 60ms são necessários para não perdermos informações durante as leituras de obstáculos.

Datasheet https://cdn.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf

**Comment by joao0606almeida** [comment]
NOTA: So e possivel se utilizar ISR nos pinos 2, 3, 18, 19, 20, 21 (com o detalhe de 20 e 21 tambem serem usados para I2C), logo, essa correcao so ocorrera caso o sensor seja delcarado com um desses pinos como parametro

Fonte: [Arduino Documentation](https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/)

**Comment by joao0606almeida** [comment]
Bom dia iago,

Sensores ultrassonicos sao definidos como objetos por esta biblioteca. Devido ao funcionamento de ISR, nao e possivel chamar uma funcao de um objeto como ISR, uma vez que o compilador nao teria como saber a qual objeto estamos se referindo. Devido a isto, funcionalidade de ISR deve ser implementada pelo usuario, ao chamar a funcao "read" para cada um de seus ultrassoms em um ISR atracado a seu pino echo.

Para facilitar essa funcionalidade, adiocionarei funcoes getEcho egetTrigger para facilmente se obter os pinos de um sensor, alem da funcao trigger para manualmente causar o trigger de um sensor sem a logica da funcao read.

A documentacao sera atualizada em breve com exemplos de ISR utilizando a biblioteca
